Repository Toronto-Tech-Mentoring/TTM-Website, pull requests merged in 2020-10, with the labels that each got.

#66 Changed padding for About Us: our roots
  src/components/AboutUs/OurRootsSection.js
Labels: bug, styling

#64 added underline to text + why tech/values driven: computer component
  src/components/WhyTechSVG/ComputerSVG.js
  src/components/WhyTechSVG/ValuesDriven.js
  src/components/WhyTechSVG/WhyTech.js
Labels: enhancement

#49 Dw/hero text section
  src/components/AboutUs/TheBottomLineSection.js
  src/components/Footer/Footer.js
  src/components/HeroText/HeroText.js
  src/components/HeroText/HeroText.module.css
  src/components/WhyTechSVG/ComputerSVG.js
  src/components/WhyTechSVG/HandsSVG.js
  src/components/WhyTechSVG/index.js
  src/images/about-us/bottom-line/people.svg
Labels: enhancement

#68 add padding to bottom line, fix left cheeto positioning and text box
  src/components/AboutUs/TheBottomLineSection.js
Labels: bug, styling

#50 Rishfilet/vital role section
  gatsby-config.js
  package-lock.json
  package.json
  src/components/AboutUs/TheBottomLineSection.js
  src/components/AboutUs/index.js
  src/components/Cheetos/cheetoLeft.js
  src/components/Cheetos/cheetoRight.js
  src/components/HeroText/HeroText.js
  src/components/Partners/PartnerCards.js
  src/components/Partners/VitalRole.js
  src/components/Partners/index.js
  src/components/SkylineSVG/SkylineHeader.js
  src/components/WhyTechSVG/ComputerSVG.js
  src/components/WhyTechSVG/ValuesDriven.js
  src/components/WhyTechSVG/index.js
  src/components/shared/ContactButton.js
  src/components/shared/GridContainer.js
  src/components/shared/GridContainerTextPic.js
  src/components/shared/ParagraphedContent.js
  src/components/shared/Question.js
  src/components/shared/SVG.js
  src/components/shared/TextBox.js
  src/components/shared/Title.js
  src/components/shared/styles/ContactButtonStyle.js
  src/components/shared/styles/GridContainerStyle.js
  src/components/shared/styles/ParagraphedContentStyle.js
  src/components/shared/styles/QuestionStyle.js
  src/components/shared/styles/SVGStyle.js
  src/components/shared/styles/TextBoxStyle.js
  src/components/shared/styles/TitleStyle.js
  src/images/cheetohs/cheetoLeft.svg
  src/images/cheetohs/cheetoRight.svg
  src/images/partners/vital-role/data_analyse.svg
Labels: WIP

#83 The links now become purple on hover
  src/components/Footer/Footer.js
  src/components/Navbar/NavTabs.js
Labels: styling

#71 Timeline fixes: padding, colour, fonts, dropshadow
  src/components/AboutUs/OurRootsSection.js
  src/components/AboutUs/TimelineSection.js
Labels: enhancement, styling
